version: 2.0

jobs:
  test:
    docker:
      - image: openjdk:7-jdk-alpine
          environment:
            JDBC_DATABASE_URL: jdbc:postgresql://localhost:5432/javacoursesdb
            JDBC_DATABASE_USERNAME: root
            JDBC_DATABASE_PASSWORD: root

      - image: circleci/postgres:9.6.5-alpine-ram
          environment:
            POSTGRES_DB: javacoursesdb

    steps:
      - checkout
      - run: ./mvnw test

  build:
    docker:
      - image: openjdk:7-jdk-alpine
          environment:
            JDBC_DATABASE_URL: jdbc:postgresql://localhost:5432/javacoursesdb
            JDBC_DATABASE_USERNAME: root
            JDBC_DATABASE_PASSWORD: root

      - image: circleci/postgres:9.6.5-alpine-ram
          environment:
            POSTGRES_DB: javacoursesdb
    steps:
      - checkout
      - run: ./mvnw -Dmaven.test.skip=true package

workflows:
  version: 2

  build-then-test:
    jobs:
      - build
      - test:
          requires:
            - build
